services:
  - type: web
    name: video-to-audio-transcribe
    env: python
    pythonVersion: 3.12
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SARVAM_API_KEY
        value: 06a7041e-d5c6-4cbc-ba13-41830608b97c
